// Curated list of countries with flag emoji + ISO code
// taxDays: days in a calendar year before tax residency applies (approximate, host-country rule)
window.COUNTRIES = [
  { code: "AR", name: "Argentina",     flag: "🇦🇷", taxDays: 183 },
  { code: "AU", name: "Australia",     flag: "🇦🇺", taxDays: 183 },
  { code: "AT", name: "Austria",       flag: "🇦🇹", taxDays: 183 },
  { code: "BE", name: "Belgium",       flag: "🇧🇪", taxDays: 183 },
  { code: "BR", name: "Brazil",        flag: "🇧🇷", taxDays: 183 },
  { code: "BG", name: "Bulgaria",      flag: "🇧🇬", taxDays: 183 },
  { code: "CA", name: "Canada",        flag: "🇨🇦", taxDays: 183 },
  { code: "CL", name: "Chile",         flag: "🇨🇱", taxDays: 183 },
  { code: "CN", name: "China",         flag: "🇨🇳", taxDays: 183 },
  { code: "CO", name: "Colombia",      flag: "🇨🇴", taxDays: 183 },
  { code: "HR", name: "Croatia",       flag: "🇭🇷", taxDays: 183 },
  { code: "CY", name: "Cyprus",        flag: "🇨🇾", taxDays: 183 },
  { code: "CZ", name: "Czechia",       flag: "🇨🇿", taxDays: 183 },
  { code: "DK", name: "Denmark",       flag: "🇩🇰", taxDays: 183 },
  { code: "EG", name: "Egypt",         flag: "🇪🇬", taxDays: 183 },
  { code: "EE", name: "Estonia",       flag: "🇪🇪", taxDays: 183 },
  { code: "FI", name: "Finland",       flag: "🇫🇮", taxDays: 183 },
  { code: "FR", name: "France",        flag: "🇫🇷", taxDays: 183 },
  { code: "GE", name: "Georgia",       flag: "🇬🇪", taxDays: 183 },
  { code: "DE", name: "Germany",       flag: "🇩🇪", taxDays: 183 },
  { code: "GR", name: "Greece",        flag: "🇬🇷", taxDays: 183 },
  { code: "HK", name: "Hong Kong",     flag: "🇭🇰", taxDays: 180 },
  { code: "HU", name: "Hungary",       flag: "🇭🇺", taxDays: 183 },
  { code: "IS", name: "Iceland",       flag: "🇮🇸", taxDays: 183 },
  { code: "IN", name: "India",         flag: "🇮🇳", taxDays: 182 },
  { code: "ID", name: "Indonesia",     flag: "🇮🇩", taxDays: 183 },
  { code: "IE", name: "Ireland",       flag: "🇮🇪", taxDays: 183 },
  { code: "IL", name: "Israel",        flag: "🇮🇱", taxDays: 183 },
  { code: "IT", name: "Italy",         flag: "🇮🇹", taxDays: 183 },
  { code: "JP", name: "Japan",         flag: "🇯🇵", taxDays: 183 },
  { code: "JO", name: "Jordan",        flag: "🇯🇴", taxDays: 183 },
  { code: "KE", name: "Kenya",         flag: "🇰🇪", taxDays: 183 },
  { code: "LV", name: "Latvia",        flag: "🇱🇻", taxDays: 183 },
  { code: "LT", name: "Lithuania",     flag: "🇱🇹", taxDays: 183 },
  { code: "LU", name: "Luxembourg",    flag: "🇱🇺", taxDays: 183 },
  { code: "MY", name: "Malaysia",      flag: "🇲🇾", taxDays: 182 },
  { code: "MT", name: "Malta",         flag: "🇲🇹", taxDays: 183 },
  { code: "MX", name: "Mexico",        flag: "🇲🇽", taxDays: 183 },
  { code: "MA", name: "Morocco",       flag: "🇲🇦", taxDays: 183 },
  { code: "NL", name: "Netherlands",   flag: "🇳🇱", taxDays: 183 },
  { code: "NZ", name: "New Zealand",   flag: "🇳🇿", taxDays: 183 },
  { code: "NO", name: "Norway",        flag: "🇳🇴", taxDays: 183 },
  { code: "PE", name: "Peru",          flag: "🇵🇪", taxDays: 183 },
  { code: "PH", name: "Philippines",   flag: "🇵🇭", taxDays: 183 },
  { code: "PL", name: "Poland",        flag: "🇵🇱", taxDays: 183 },
  { code: "PT", name: "Portugal",      flag: "🇵🇹", taxDays: 183 },
  { code: "QA", name: "Qatar",         flag: "🇶🇦", taxDays: 183 },
  { code: "RO", name: "Romania",       flag: "🇷🇴", taxDays: 183 },
  { code: "RS", name: "Serbia",        flag: "🇷🇸", taxDays: 183 },
  { code: "SG", name: "Singapore",     flag: "🇸🇬", taxDays: 183 },
  { code: "SK", name: "Slovakia",      flag: "🇸🇰", taxDays: 183 },
  { code: "SI", name: "Slovenia",      flag: "🇸🇮", taxDays: 183 },
  { code: "ZA", name: "South Africa",  flag: "🇿🇦", taxDays: 183 },
  { code: "KR", name: "South Korea",   flag: "🇰🇷", taxDays: 183 },
  { code: "ES", name: "Spain",         flag: "🇪🇸", taxDays: 183 },
  { code: "SE", name: "Sweden",        flag: "🇸🇪", taxDays: 183 },
  { code: "CH", name: "Switzerland",   flag: "🇨🇭", taxDays: 183 },
  { code: "TW", name: "Taiwan",        flag: "🇹🇼", taxDays: 183 },
  { code: "TH", name: "Thailand",      flag: "🇹🇭", taxDays: 180 },
  { code: "TR", name: "Türkiye",       flag: "🇹🇷", taxDays: 183 },
  { code: "AE", name: "UAE",           flag: "🇦🇪", taxDays: 183 },
  { code: "UA", name: "Ukraine",       flag: "🇺🇦", taxDays: 183 },
  { code: "GB", name: "United Kingdom",flag: "🇬🇧", taxDays: 183 },
  { code: "US", name: "United States", flag: "🇺🇸", taxDays: 183 },
  { code: "UY", name: "Uruguay",       flag: "🇺🇾", taxDays: 183 },
  { code: "VN", name: "Vietnam",       flag: "🇻🇳", taxDays: 183 },
];

window.COUNTRY_BY_CODE = Object.fromEntries(window.COUNTRIES.map(c => [c.code, c]));
